version: '3.7'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./static:/app/static/

    
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - ./static:/var/www/django/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    